name: Frontend S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Nodejs v14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install Dependencies
      - run: yarn

      - name: Generate Project Build
      - run: yarn build

      # - name: Execute all tests
      # - run: yarn test

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Update Bucket
      #   run: aws s3 cp build/ s3://angelo-ci-cd-react-app --recursive
